steps:
  # Build using Cloud Native Buildpacks
  - id: Buildpack
    name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/finbossapi:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:latest
      - --network=cloudbuild
      - --path=.
    env:
      - 'BUILDER=gcr.io/buildpacks/builder:latest'

  # Push image to Artifact Registry
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/finbossapi:$COMMIT_SHA

  # Deploy to Cloud Run
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - finbossapi
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/finbossapi:$COMMIT_SHA
      - --region=us-central1
      - --quiet
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/finbossapi:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
